//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RMPModel", "FK_Feedbacks_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataLayer.User), "Feedback", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.Feedback), true)]
[assembly: EdmRelationshipAttribute("RMPModel", "FK_PasswordQueries_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataLayer.User), "PasswordQuery", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.PasswordQuery), true)]
[assembly: EdmRelationshipAttribute("RMPModel", "FK_PasswordQuery_WebSite", "WebSite", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataLayer.WebSite), "PasswordQuery", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.PasswordQuery), true)]
[assembly: EdmRelationshipAttribute("RMPModel", "FK_SavedQueries_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataLayer.User), "SavedUserQuery", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.SavedUserQuery), true)]
[assembly: EdmRelationshipAttribute("RMPModel", "FK_SavedQueries_WebSites", "WebSite", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataLayer.WebSite), "SavedUserQuery", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.SavedUserQuery), true)]

#endregion

namespace DataLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RMPEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RMPEntities object using the connection string found in the 'RMPEntities' section of the application configuration file.
        /// </summary>
        public RMPEntities() : base("name=RMPEntities", "RMPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RMPEntities object.
        /// </summary>
        public RMPEntities(string connectionString) : base(connectionString, "RMPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RMPEntities object.
        /// </summary>
        public RMPEntities(EntityConnection connection) : base(connection, "RMPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Caption> Captions
        {
            get
            {
                if ((_Captions == null))
                {
                    _Captions = base.CreateObjectSet<Caption>("Captions");
                }
                return _Captions;
            }
        }
        private ObjectSet<Caption> _Captions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Feedback> Feedbacks
        {
            get
            {
                if ((_Feedbacks == null))
                {
                    _Feedbacks = base.CreateObjectSet<Feedback>("Feedbacks");
                }
                return _Feedbacks;
            }
        }
        private ObjectSet<Feedback> _Feedbacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ListElement> ListElements
        {
            get
            {
                if ((_ListElements == null))
                {
                    _ListElements = base.CreateObjectSet<ListElement>("ListElements");
                }
                return _ListElements;
            }
        }
        private ObjectSet<ListElement> _ListElements;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Messages
        {
            get
            {
                if ((_Messages == null))
                {
                    _Messages = base.CreateObjectSet<Message>("Messages");
                }
                return _Messages;
            }
        }
        private ObjectSet<Message> _Messages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PasswordQuery> PasswordQueries
        {
            get
            {
                if ((_PasswordQueries == null))
                {
                    _PasswordQueries = base.CreateObjectSet<PasswordQuery>("PasswordQueries");
                }
                return _PasswordQueries;
            }
        }
        private ObjectSet<PasswordQuery> _PasswordQueries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SavedUserQuery> SavedUserQueries
        {
            get
            {
                if ((_SavedUserQueries == null))
                {
                    _SavedUserQueries = base.CreateObjectSet<SavedUserQuery>("SavedUserQueries");
                }
                return _SavedUserQueries;
            }
        }
        private ObjectSet<SavedUserQuery> _SavedUserQueries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Title> Titles
        {
            get
            {
                if ((_Titles == null))
                {
                    _Titles = base.CreateObjectSet<Title>("Titles");
                }
                return _Titles;
            }
        }
        private ObjectSet<Title> _Titles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WebSite> WebSites
        {
            get
            {
                if ((_WebSites == null))
                {
                    _WebSites = base.CreateObjectSet<WebSite>("WebSites");
                }
                return _WebSites;
            }
        }
        private ObjectSet<WebSite> _WebSites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GetMostUsedWebSite> GetMostUsedWebSites
        {
            get
            {
                if ((_GetMostUsedWebSites == null))
                {
                    _GetMostUsedWebSites = base.CreateObjectSet<GetMostUsedWebSite>("GetMostUsedWebSites");
                }
                return _GetMostUsedWebSites;
            }
        }
        private ObjectSet<GetMostUsedWebSite> _GetMostUsedWebSites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GetUserSavedWebSite> GetUserSavedWebSites
        {
            get
            {
                if ((_GetUserSavedWebSites == null))
                {
                    _GetUserSavedWebSites = base.CreateObjectSet<GetUserSavedWebSite>("GetUserSavedWebSites");
                }
                return _GetUserSavedWebSites;
            }
        }
        private ObjectSet<GetUserSavedWebSite> _GetUserSavedWebSites;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Captions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCaptions(Caption caption)
        {
            base.AddObject("Captions", caption);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Feedbacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeedbacks(Feedback feedback)
        {
            base.AddObject("Feedbacks", feedback);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ListElements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToListElements(ListElement listElement)
        {
            base.AddObject("ListElements", listElement);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessages(Message message)
        {
            base.AddObject("Messages", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PasswordQueries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPasswordQueries(PasswordQuery passwordQuery)
        {
            base.AddObject("PasswordQueries", passwordQuery);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SavedUserQueries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSavedUserQueries(SavedUserQuery savedUserQuery)
        {
            base.AddObject("SavedUserQueries", savedUserQuery);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Titles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTitles(Title title)
        {
            base.AddObject("Titles", title);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebSites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebSites(WebSite webSite)
        {
            base.AddObject("WebSites", webSite);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GetMostUsedWebSites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGetMostUsedWebSites(GetMostUsedWebSite getMostUsedWebSite)
        {
            base.AddObject("GetMostUsedWebSites", getMostUsedWebSite);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GetUserSavedWebSites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGetUserSavedWebSites(GetUserSavedWebSite getUserSavedWebSite)
        {
            base.AddObject("GetUserSavedWebSites", getUserSavedWebSite);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="Caption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Caption : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Caption object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static Caption CreateCaption(global::System.Int32 id, global::System.String name, global::System.String text)
        {
            Caption caption = new Caption();
            caption.Id = id;
            caption.Name = name;
            caption.Text = text;
            return caption;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="Feedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Feedback : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Feedback object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="topic">Initial value of the Topic property.</param>
        /// <param name="feedbackText">Initial value of the FeedbackText property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        public static Feedback CreateFeedback(global::System.Int32 id, global::System.String topic, global::System.String feedbackText, global::System.DateTime createdAt)
        {
            Feedback feedback = new Feedback();
            feedback.Id = id;
            feedback.Topic = topic;
            feedback.FeedbackText = feedbackText;
            feedback.CreatedAt = createdAt;
            return feedback;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Topic
        {
            get
            {
                return _Topic;
            }
            set
            {
                OnTopicChanging(value);
                ReportPropertyChanging("Topic");
                _Topic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Topic");
                OnTopicChanged();
            }
        }
        private global::System.String _Topic;
        partial void OnTopicChanging(global::System.String value);
        partial void OnTopicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FeedbackText
        {
            get
            {
                return _FeedbackText;
            }
            set
            {
                OnFeedbackTextChanging(value);
                ReportPropertyChanging("FeedbackText");
                _FeedbackText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FeedbackText");
                OnFeedbackTextChanged();
            }
        }
        private global::System.String _FeedbackText;
        partial void OnFeedbackTextChanging(global::System.String value);
        partial void OnFeedbackTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int64> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int64> value);
        partial void OnUserIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_Feedbacks_Users", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_Feedbacks_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_Feedbacks_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_Feedbacks_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("RMPModel.FK_Feedbacks_Users", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="GetMostUsedWebSite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GetMostUsedWebSite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetMostUsedWebSite object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        public static GetMostUsedWebSite CreateGetMostUsedWebSite(global::System.String name)
        {
            GetMostUsedWebSite getMostUsedWebSite = new GetMostUsedWebSite();
            getMostUsedWebSite.Name = name;
            return getMostUsedWebSite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cnt
        {
            get
            {
                return _cnt;
            }
            set
            {
                OncntChanging(value);
                ReportPropertyChanging("cnt");
                _cnt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cnt");
                OncntChanged();
            }
        }
        private Nullable<global::System.Int32> _cnt;
        partial void OncntChanging(Nullable<global::System.Int32> value);
        partial void OncntChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="GetUserSavedWebSite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GetUserSavedWebSite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetUserSavedWebSite object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="algorithmLevel">Initial value of the AlgorithmLevel property.</param>
        /// <param name="charCount">Initial value of the CharCount property.</param>
        public static GetUserSavedWebSite CreateGetUserSavedWebSite(global::System.Int64 id, global::System.Int64 userId, global::System.String userName, global::System.String name, global::System.String algorithmLevel, global::System.Int32 charCount)
        {
            GetUserSavedWebSite getUserSavedWebSite = new GetUserSavedWebSite();
            getUserSavedWebSite.Id = id;
            getUserSavedWebSite.UserId = userId;
            getUserSavedWebSite.UserName = userName;
            getUserSavedWebSite.Name = name;
            getUserSavedWebSite.AlgorithmLevel = algorithmLevel;
            getUserSavedWebSite.CharCount = charCount;
            return getUserSavedWebSite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AlgorithmLevel
        {
            get
            {
                return _AlgorithmLevel;
            }
            set
            {
                if (_AlgorithmLevel != value)
                {
                    OnAlgorithmLevelChanging(value);
                    ReportPropertyChanging("AlgorithmLevel");
                    _AlgorithmLevel = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AlgorithmLevel");
                    OnAlgorithmLevelChanged();
                }
            }
        }
        private global::System.String _AlgorithmLevel;
        partial void OnAlgorithmLevelChanging(global::System.String value);
        partial void OnAlgorithmLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CharCount
        {
            get
            {
                return _CharCount;
            }
            set
            {
                if (_CharCount != value)
                {
                    OnCharCountChanging(value);
                    ReportPropertyChanging("CharCount");
                    _CharCount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CharCount");
                    OnCharCountChanged();
                }
            }
        }
        private global::System.Int32 _CharCount;
        partial void OnCharCountChanging(global::System.Int32 value);
        partial void OnCharCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="ListElement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ListElement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ListElement object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ListElement CreateListElement(global::System.Int32 id, global::System.String name)
        {
            ListElement listElement = new ListElement();
            listElement.Id = id;
            listElement.Name = name;
            return listElement;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static Message CreateMessage(global::System.Int32 id, global::System.String name, global::System.String text)
        {
            Message message = new Message();
            message.Id = id;
            message.Name = name;
            message.Text = text;
            return message;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="PasswordQuery")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PasswordQuery : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PasswordQuery object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="webSiteId">Initial value of the WebSiteId property.</param>
        /// <param name="charCount">Initial value of the CharCount property.</param>
        public static PasswordQuery CreatePasswordQuery(global::System.Int64 id, global::System.Int64 webSiteId, global::System.Int32 charCount)
        {
            PasswordQuery passwordQuery = new PasswordQuery();
            passwordQuery.Id = id;
            passwordQuery.WebSiteId = webSiteId;
            passwordQuery.CharCount = charCount;
            return passwordQuery;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 WebSiteId
        {
            get
            {
                return _WebSiteId;
            }
            set
            {
                OnWebSiteIdChanging(value);
                ReportPropertyChanging("WebSiteId");
                _WebSiteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebSiteId");
                OnWebSiteIdChanged();
            }
        }
        private global::System.Int64 _WebSiteId;
        partial void OnWebSiteIdChanging(global::System.Int64 value);
        partial void OnWebSiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int64> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int64> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GeneratedAt
        {
            get
            {
                return _GeneratedAt;
            }
            set
            {
                OnGeneratedAtChanging(value);
                ReportPropertyChanging("GeneratedAt");
                _GeneratedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneratedAt");
                OnGeneratedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _GeneratedAt;
        partial void OnGeneratedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnGeneratedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AlgorithmType
        {
            get
            {
                return _AlgorithmType;
            }
            set
            {
                OnAlgorithmTypeChanging(value);
                ReportPropertyChanging("AlgorithmType");
                _AlgorithmType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AlgorithmType");
                OnAlgorithmTypeChanged();
            }
        }
        private global::System.String _AlgorithmType;
        partial void OnAlgorithmTypeChanging(global::System.String value);
        partial void OnAlgorithmTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CharCount
        {
            get
            {
                return _CharCount;
            }
            set
            {
                OnCharCountChanging(value);
                ReportPropertyChanging("CharCount");
                _CharCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CharCount");
                OnCharCountChanged();
            }
        }
        private global::System.Int32 _CharCount;
        partial void OnCharCountChanging(global::System.Int32 value);
        partial void OnCharCountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_PasswordQueries_Users", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_PasswordQueries_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_PasswordQueries_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_PasswordQueries_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("RMPModel.FK_PasswordQueries_Users", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_PasswordQuery_WebSite", "WebSite")]
        public WebSite WebSite
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebSite>("RMPModel.FK_PasswordQuery_WebSite", "WebSite").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebSite>("RMPModel.FK_PasswordQuery_WebSite", "WebSite").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WebSite> WebSiteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebSite>("RMPModel.FK_PasswordQuery_WebSite", "WebSite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WebSite>("RMPModel.FK_PasswordQuery_WebSite", "WebSite", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="SavedUserQuery")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SavedUserQuery : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SavedUserQuery object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="webSiteId">Initial value of the WebSiteId property.</param>
        /// <param name="algorithmLevel">Initial value of the AlgorithmLevel property.</param>
        /// <param name="applicationSource">Initial value of the ApplicationSource property.</param>
        /// <param name="charCount">Initial value of the CharCount property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        public static SavedUserQuery CreateSavedUserQuery(global::System.Int64 id, global::System.String name, global::System.Int64 userId, global::System.String userName, global::System.Int64 webSiteId, global::System.String algorithmLevel, global::System.String applicationSource, global::System.Int32 charCount, global::System.DateTime createdAt)
        {
            SavedUserQuery savedUserQuery = new SavedUserQuery();
            savedUserQuery.Id = id;
            savedUserQuery.Name = name;
            savedUserQuery.UserId = userId;
            savedUserQuery.UserName = userName;
            savedUserQuery.WebSiteId = webSiteId;
            savedUserQuery.AlgorithmLevel = algorithmLevel;
            savedUserQuery.ApplicationSource = applicationSource;
            savedUserQuery.CharCount = charCount;
            savedUserQuery.CreatedAt = createdAt;
            return savedUserQuery;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 WebSiteId
        {
            get
            {
                return _WebSiteId;
            }
            set
            {
                OnWebSiteIdChanging(value);
                ReportPropertyChanging("WebSiteId");
                _WebSiteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebSiteId");
                OnWebSiteIdChanged();
            }
        }
        private global::System.Int64 _WebSiteId;
        partial void OnWebSiteIdChanging(global::System.Int64 value);
        partial void OnWebSiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AlgorithmLevel
        {
            get
            {
                return _AlgorithmLevel;
            }
            set
            {
                OnAlgorithmLevelChanging(value);
                ReportPropertyChanging("AlgorithmLevel");
                _AlgorithmLevel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AlgorithmLevel");
                OnAlgorithmLevelChanged();
            }
        }
        private global::System.String _AlgorithmLevel;
        partial void OnAlgorithmLevelChanging(global::System.String value);
        partial void OnAlgorithmLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationSource
        {
            get
            {
                return _ApplicationSource;
            }
            set
            {
                OnApplicationSourceChanging(value);
                ReportPropertyChanging("ApplicationSource");
                _ApplicationSource = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApplicationSource");
                OnApplicationSourceChanged();
            }
        }
        private global::System.String _ApplicationSource;
        partial void OnApplicationSourceChanging(global::System.String value);
        partial void OnApplicationSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CharCount
        {
            get
            {
                return _CharCount;
            }
            set
            {
                OnCharCountChanging(value);
                ReportPropertyChanging("CharCount");
                _CharCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CharCount");
                OnCharCountChanged();
            }
        }
        private global::System.Int32 _CharCount;
        partial void OnCharCountChanging(global::System.Int32 value);
        partial void OnCharCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedAt
        {
            get
            {
                return _UpdatedAt;
            }
            set
            {
                OnUpdatedAtChanging(value);
                ReportPropertyChanging("UpdatedAt");
                _UpdatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedAt");
                OnUpdatedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedAt;
        partial void OnUpdatedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedAtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_SavedQueries_Users", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_SavedQueries_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_SavedQueries_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("RMPModel.FK_SavedQueries_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("RMPModel.FK_SavedQueries_Users", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_SavedQueries_WebSites", "WebSite")]
        public WebSite WebSite
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebSite>("RMPModel.FK_SavedQueries_WebSites", "WebSite").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebSite>("RMPModel.FK_SavedQueries_WebSites", "WebSite").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WebSite> WebSiteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebSite>("RMPModel.FK_SavedQueries_WebSites", "WebSite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WebSite>("RMPModel.FK_SavedQueries_WebSites", "WebSite", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="Title")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Title : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Title object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static Title CreateTitle(global::System.Int32 id, global::System.String name, global::System.String text)
        {
            Title title = new Title();
            title.Id = id;
            title.Name = name;
            title.Text = text;
            return title;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="loginName">Initial value of the LoginName property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static User CreateUser(global::System.Int64 id, global::System.String name, global::System.String emailAddress, global::System.String loginName, global::System.DateTime createdAt, global::System.String password)
        {
            User user = new User();
            user.Id = id;
            user.Name = name;
            user.EmailAddress = emailAddress;
            user.LoginName = loginName;
            user.CreatedAt = createdAt;
            user.Password = password;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BornAt
        {
            get
            {
                return _BornAt;
            }
            set
            {
                OnBornAtChanging(value);
                ReportPropertyChanging("BornAt");
                _BornAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BornAt");
                OnBornAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _BornAt;
        partial void OnBornAtChanging(Nullable<global::System.DateTime> value);
        partial void OnBornAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_Feedbacks_Users", "Feedback")]
        public EntityCollection<Feedback> Feedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Feedback>("RMPModel.FK_Feedbacks_Users", "Feedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Feedback>("RMPModel.FK_Feedbacks_Users", "Feedback", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_PasswordQueries_Users", "PasswordQuery")]
        public EntityCollection<PasswordQuery> PasswordQueries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PasswordQuery>("RMPModel.FK_PasswordQueries_Users", "PasswordQuery");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PasswordQuery>("RMPModel.FK_PasswordQueries_Users", "PasswordQuery", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_SavedQueries_Users", "SavedUserQuery")]
        public EntityCollection<SavedUserQuery> SavedUserQueries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SavedUserQuery>("RMPModel.FK_SavedQueries_Users", "SavedUserQuery");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SavedUserQuery>("RMPModel.FK_SavedQueries_Users", "SavedUserQuery", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RMPModel", Name="WebSite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WebSite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WebSite object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static WebSite CreateWebSite(global::System.Int64 id, global::System.String name)
        {
            WebSite webSite = new WebSite();
            webSite.Id = id;
            webSite.Name = name;
            return webSite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_PasswordQuery_WebSite", "PasswordQuery")]
        public EntityCollection<PasswordQuery> PasswordQueries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PasswordQuery>("RMPModel.FK_PasswordQuery_WebSite", "PasswordQuery");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PasswordQuery>("RMPModel.FK_PasswordQuery_WebSite", "PasswordQuery", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RMPModel", "FK_SavedQueries_WebSites", "SavedUserQuery")]
        public EntityCollection<SavedUserQuery> SavedUserQueries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SavedUserQuery>("RMPModel.FK_SavedQueries_WebSites", "SavedUserQuery");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SavedUserQuery>("RMPModel.FK_SavedQueries_WebSites", "SavedUserQuery", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
